### ISSUE TITLE
<tab>public conflicts with popular linters

### ISSUE THREAD

**Issue by timmackey** [aljazsim/vs-code-typescript-class-organizer#1]
popular linters (TSLint) marks all tab characters as errors.
Suggestion: a configuration setting to prepend 'public' with tab or n spaces.

**Comment by aljazsim** [comment]
Hi Tim.

I'm really sorry about not responding to all your issues. For some reason GitHub hasn't been sending me any notifications and I wasn't aware of them. I'll try to tackle them over the weekend.

**Comment by aljazsim** [comment]
Fixed, try it out in version 1.0.9.

**Comment by timmackey** [comment]
Didn't find a configuration option in version 1.0.9
Start of line spaces are replaced with tabs.  This issue does not appear to be resolved.
Also please note 'egamma TSLint' has been deprecated in favor of 'Microsoft TSLint'.
Thank you.

**Comment by aljazsim** [comment]
I've made a change, so the extension tries to find out what the identation style is from the source. The problem is that can be set in vs code settings, .editorconfig or tslint file. Try it out in 1.0.10.
