### ISSUE TITLE
Is there any cli version for the same transformations?

### ISSUE THREAD

**Issue by vvscode** [aljazsim/vs-code-typescript-class-organizer#10]
Or is it possible to run commands from command line?

**Comment by aljazsim** [comment]
Hi Vasiliy.

Currently that is not possible, but the VS Code related logic is separate from the actual transformation logic, so creating a CLI access to the functionality shouldn't be too difficult.

**Comment by vvscode** [comment]
@aljazsim  would you mind me taking your source for this purpose?

**Comment by aljazsim** [comment]
> 
> 
> @aljazsim would you mind me taking your source for this purpose?

Of course you can.

**Comment by vvscode** [comment]
https://www.npmjs.com/package/cli-typescript-class-organizer
