### ISSUE TITLE
remove count in region && accessor before ctor

### ISSUE THREAD

**Issue by pillont** [aljazsim/vs-code-typescript-class-organizer#14]
Hello,

My team want to use your tool, but we need to have more config to match with our needs.
So I did a new MR to add there : 
https://github.com/aljazsim/vs-code-typescript-class-organizer/pull/13/files

Can you please, take a look on this changes and make a feedback to update your fabulous tool together ? :D

Thanks in advance !

**Comment by aljazsim** [comment]
Thanks pillont. You've made a few great features. I'll publish the changes to the market place right away.
