### ISSUE TITLE
Option to put constructor before methods

### ISSUE THREAD

**Issue by testpossessed** [aljazsim/vs-code-typescript-class-organizer#15]
Great extension, very helpful.

Could we have some options to control the ordering of members, or at least to put the constructor before methods.

tsLint insists on the constructor being before public methods and I prefer this convention so don't want to turn off the rule.

I have always organised my code like this regardless of language and would like to be able to control the order.

private fields
constructor
public fields/properties
public methods
private methods

Happy to look at a creating a PR if you prefer that approach.

**Comment by aljazsim** [comment]
Hi Mike.

That sounds like a good idea. I'll see what can I do.

**Comment by aljazsim** [comment]
Hi Mike.

I've added the ability for custom member grouping and ordering. Check out the "organize-member" branch and let me know what you think. Instructions are included in the Readme file.

**Comment by aljazsim** [comment]
Published in version 1.0.15.

**Comment by testpossessed** [comment]
Excellent thanks for the fast response.

I have noticed one issue with the new feature, will post a new issue about it.
