### ISSUE TITLE
Run by Terminal & Add "publicImplementedMethods" for "tsco.memberOrder"

### ISSUE THREAD

**Issue by thanhhoa214** [aljazsim/vs-code-typescript-class-organizer#21]
## Thank you so much !

On the other hand, I hope you can implement 2 more features, there're practices & really needed.
### 1. Run by Terminal

- If I can combine your tool with `pre-commit-hook`, it will be awesome probably.

### 2. Add "publicImplementedMethods" for "tsco.memberOrder"

- I work as an Ionic Developer, so TypeScript is my right hand and the inheritance principle also. I need to order my life-cycle functions.

`Eureka. You make my day`

**Comment by aljazsim** [comment]
Hi Hòa.

Thank you for the kind words. It is always rewarding to hear feedback from the users :) 

1. Someone already made a command line version of this addin: https://github.com/vvscode/cli-typescript-class-organizer. 

2. As for feature request 2, I am not quite clear on what it is that you would like to achieve. Would you be able to elaborate in more details?

**Comment by thanhhoa214** [comment]
Many thanks your response. 
As I mentioned, visualize by picture below. I would like to group all "publicImplementedMethods" (with my mean is functions under-control of `implements` or `extends` keyword).
Any confused please talk to me.

<img width="789" alt="Screen Shot 2020-05-17 at 6 32 22 PM" src="https://user-images.githubusercontent.com/32329202/82143261-c196d900-986c-11ea-971e-45e54db80fe6.png">

**Comment by aljazsim** [comment]
I see. As I'm currently overwhelmed with my work I invite you to implement this feature yourself and I will be more than happy to help out with any advice you might need.

**Comment by thanhhoa214** [comment]
I'll try & send pull request when completed.
