### ISSUE TITLE
Missing public incorrectly added after static

### ISSUE THREAD

**Issue by entr0cks** [aljazsim/vs-code-typescript-class-organizer#22]
The "public" modifier, that gets added when missing by default, was added between "static" and the property name.
It's supposed to be before static.
![image](https://user-images.githubusercontent.com/5465193/86943932-b9159d00-c14f-11ea-9e2c-37b4eb78ec26.png)

Note: can be disabled - #5, as can regions - thanks you for the nice extension :)

**Comment by aljazsim** [comment]
Please upgrade to version 10.0.21.
