### ISSUE TITLE
Order by Decorator

### ISSUE THREAD

**Issue by dereklin** [aljazsim/vs-code-typescript-class-organizer#24]
Can we order by decorator in addition to order by access level?  For example, I would like to move 

```
@ViewChild('test') private test: Test;
```
above all member properties

And it would be nice if we can control the order of the decorators.  For example, we can choose to put @Input on top or at the bottom of @ViewChild

If not, can we have some ignore blocks where the organizer won't touch if we manually order a portion of the code?  Maybe like 

```
// vs-code-typescript-class-organizer:disable

some manually order code...

// vs-code-typescript-class-organizer:enable

```

**Comment by aljazsim** [comment]
Hi dereklin.

This is a good idea. Considering I'm overwhelmed by other work at the moment, I encourage you to implement the functionality yourself and submit a PR and I'll provide guidance if necessary.

**Comment by dereklin** [comment]
Hi @aljazsim, could you show me how to set up my environment so that I can try formatting my code using a "live" project?  I want to get to the point where I can get fast/live feedback when developing.

**Comment by aljazsim** [comment]
Sure. Here are the steps:
1. check out this repo
2. open the source directory in VS Code
3. press F5 (more on debugging: https://code.visualstudio.com/api/get-started/your-first-extension)
4. in the new "debugged" instance of VS code open a *.ts file
5. run the command to order the class/interface members (via command menu (F1 -> organize current file, context menu or a shortcut: Ctrl + Shift + O)
5. any breakpoints you might have set will be hit by the debugger

**Comment by aljazsim** [comment]
There's a setting that will do just that: 
![image](https://user-images.githubusercontent.com/36719693/183240425-67dc75f5-e251-450b-8baa-35743d298b9d.png)
