### ISSUE TITLE
unicode gets messed up

### ISSUE THREAD

**Issue by Schokokex** [aljazsim/vs-code-typescript-class-organizer#27]
got a string like `"📋 Clipboard"` which is getting messed up.

Still many thanks for the addon!
Might get myself into some pull requests some time.

**Comment by aljazsim** [comment]
Hi @Schokokex. I've tried to use the string you've provided as an example and haven't had any side-effects from it. If you can perhaps provide me with a full file sample with a before and broken after version, I'll investigate further.
