### ISSUE TITLE
Order functions based on their dependancies not by name. 

### ISSUE THREAD

**Issue by mhamri** [aljazsim/vs-code-typescript-class-organizer#28]
Currently, functions are being ordered by name, this disrupts how a code being used/read. now need to go up and down in a file to maintain the functions. Though it's doable, it's not favorable. 

If it's doable, I prefer something like codmaid. the order is based on the dependency and not the name. The methods of least dependency will be at the top and the rest follows. 

or one option that lets the user choose the order-algorithm or disable it.

**Comment by mhamri** [comment]
this is another example I found that in fact is a bug

![image](https://user-images.githubusercontent.com/8991783/110212391-1aa42c00-7ed6-11eb-8a38-f75d7202c8dc.png)

**Comment by aljazsim** [comment]
Hi Mohammad. I'm not quite sure I understand your sorting idea, but you're welcome to implement it yourself and create a PR. As far as the bug goes, the properties are correctly ordered, and if you moved your initialization code to a constructor, you would not get a compile error.

**Comment by mhamri** [comment]
@aljazsim how the bug is correctly ordered? the initialization came after the usage. it should be first the initialization, then the usage. 

The `selectedProject$` should come before the `activityGroupByDate$` as it depends on it. But since the order mechanism is by alphabet, `a` is coming before the `s`, and cause this bug

here is an example to test it on your own 

this is the correct :

```typescript
class SubClass {
    public method1(){}
}

class SampleClass {
    zProperty= new SubClass();
    aProperty= this.aProperty.method1();
}
```

but what the addon is organizing is like this 

```typescript
class SubClass {
    public method1(){}
}

class SampleClass {
    aProperty= this.aProperty.method1();
    zProperty= new SubClass();
}
```


in typescript order of the properties matters.
