### ISSUE TITLE
Would be great if it can read ordering from .eslintrc.js

### ISSUE THREAD

**Issue by giano** [aljazsim/vs-code-typescript-class-organizer#29]
Thank you for this extension. Saved me a lot of time already.

Would be a killer feature if it can infer members ordering from eslint/tslint (specifically from [member-ordering rule](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/member-ordering.md))

if not present it could use the default rule if @typescript-eslint plugin is installed

Never wrote vscode extension, but can help for beta testing.

**Comment by oobleck** [comment]
Amen for this. This would be rad.

**Comment by aljazsim** [comment]
Unfortunately this extension already has so many settings making it complicated as it is. You're welcome to fork the repo and give it a try yourself!
