### ISSUE TITLE
commented-out property not recognized

### ISSUE THREAD

**Issue by timmackey** [aljazsim/vs-code-typescript-class-organizer#3]
when functions and properties are commented out, the first property is not recognized as being commented.

	public // tick_then_delay = 200;
    // tick_then_before_delay = 220;

User must edited code to remove 'public' descriptor.
Same for functions:
	public // schedules a view refresh to ensure display catches up
    // tick_then(fn: () => any) {
    //   this.curr_tick = Date();
    //     if (this.curr_tick < this.prev_tick + this.tick_then_delay) {
    //         return;
    //     }
    //     this.prev_tick = this.curr_tick;
    //     console.log('TtmDashboardComponent: tick_then()');
    //     setTimeout(fn, 100);
    // }

**Comment by aljazsim** [comment]
Fixed issue, try it out in version 1.0.9.
