### ISSUE TITLE
Organizer does not work within *.spec.ts file

### ISSUE THREAD

**Issue by PirasannaRavi** [aljazsim/vs-code-typescript-class-organizer#32]
Hello team, I see that the extension does not work for all ts files. For example it does not work in the *.spec.ts files of Angular Unit Tests

**Comment by aljazsim** [comment]
Hi @PirasannaRavi. Spec files are unit tests defined as a return from a describe method and as such aren't classes, interfaces or types. The TSCO addin does not change the code within method as that could have unwanted effects on the logic within.
