### ISSUE TITLE
Typescript 4.4 private identifiers & addPublicModifierIfMissing

### ISSUE THREAD

**Issue by mp3three** [aljazsim/vs-code-typescript-class-organizer#33]
The extension wants to add a `public` in front of class properties marked as private, which creates a typescript error.

```typescript
export class Example {
 // This should not have public added
  #privateProperty = true; 
  // This one should have it added
  anotherProperty = false;
}
```

For the purposes of sorting, these act the same as private properties. Currently sorting has them being grouped together with the public properties

**Comment by aljazsim** [comment]
Hi @mp3three. Please check the TS spec: by default the members are considered public (when the access modifier is omitted): https://www.typescriptlang.org/docs/handbook/2/classes.html#public, hence this is the correct behavior.

**Comment by mp3three** [comment]
I don't use the extension anymore, but you should continue reading that page until this this link under private field caveats

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields


Fields with this format are always private at a language level and the modifier is wrong

**Comment by aljazsim** [comment]
I see. I was unaware of this special naming convention. Thank you for pointing it out, I'll update the code in the next version.
