### ISSUE TITLE
Add blank line before properties, even when "useRegions" is set to false?

### ISSUE THREAD

**Issue by birgersp** [aljazsim/vs-code-typescript-class-organizer#36]
Hi,

Amazing extension, thank you very much for making this.

In our codebase we don't use regions (though we do group member types ofc), so "useRegions" is set to false.

So this code:
```
export class SomeClass {
	private y = 0
	public x = 0
}
```

Gets formatted into this (notice there is no blank line between the class header and the x property):
```
export class SomeClass {
	public x = 0

	private y = 0
}
```

But what I want it to look like is this (blank line on line 2):
```
export class SomeClass {

	public x = 0

	private y = 0
}
```

If I enable "useRegions" I get this:
```
export class SomeClass {
	// #region Properties (2)

	public x = 0

	private y = 0

	// #endregion Properties (2)
}
```

Which is kinda what I want, but without the regions.

**Comment by aljazsim** [comment]
Hi birgersp. This behavior is by design, all redundant lines are removed when organizing members.

**Comment by birgersp** [comment]
I see what you mean by saying that the line is redundant.

But why is there a blank line then, here:

```
	// #region Properties (2)

	public x = 0
```

?

**Comment by aljazsim** [comment]
I've taken the inspiration for this feature from a C# plugin that I've been using for many years (code maid), that does the exact same thing; however, it uses regions, a feature not present in TS. That is why I had to use comments and if the comment would be generated on the top of the first member of the group (in your example property x) without a blank line in between, it could be considered, that the comment is describing the property (or relates to the property), which it is not; hence the empty line in between to visually separate member groups (properties, methods, ...).

**Comment by birgersp** [comment]
I see. I'm also a big fan of CodeMaid btw. I am pretty sure it had a blank line under the class header, even when regions were turned off.

So, do you *prefer* that there is no blank line under the class header?

I mean do you prefer this (example A):

```
export class SomeClass {
	public x = 0

	private y = 0
}
```

Over this (example B)?:

```
export class SomeClass {

	public x = 0

	private y = 0
}
```

Would you consider merging a PR where that makes the extension keep a blank line, like example B? It could be a configurable setting (where default is current behaviour, no blank line)

**Comment by aljazsim** [comment]
I prefer consistency above all, and if there should be an empty line after an opening curly brace for a class declaration, it should be before every opening curly brace (including if statements, for loops, method declarations, etc.). But then there should be a line before every closing brace as well and here things already get messy. I do agree the default JS/TS formatting is ugly and makes code harder to read, so personally I prefer the C# approach with keeping opening curly braces on a separate line; this gives me the extra line between the class declaration and first property as well as consistency with closing curly braces that are always on a separate line. If you feel really strongly about the empty line, feel free to submit a PR and be sure to make a setting for it, that is by default set to false.  And like I said: there should be an empty line after every opening curly brace to keep it consistent.

**Comment by birgersp** [comment]
That's totally fair.

But I think the governing rule here would be 

"each group has an empty line above it"

Which, currently is enforced except for the topmost group of properties, I think?

![image](https://user-images.githubusercontent.com/5260237/183414969-468a1a6e-0f13-4dec-9371-abadcda4a175.png)

**Comment by aljazsim** [comment]
Correct!

**Comment by birgersp** [comment]
Would you agree that current behaviour is a bit inconsistent (when useRegions is disabled)?

I mean, why doesn't the topmost group have an empty line above it, when the other groups has it?

Should a "fix" for this this still be a setting?

**Comment by aljazsim** [comment]
That is the expected behavior:  there is a blank line between members to separate them. Properties are a bit different, since they're grouped together by access modifiers, but there's not line above the first one, because there's nothing above to separate it from. To be clear: there is no empty lines above groups; there is a line **between** them.

**Comment by birgersp** [comment]
Understood.

So then my PR will include a new setting: "addEmptyLineAboveFirstGroup".
