### ISSUE TITLE
@Listeners should not be made public

### ISSUE THREAD

**Issue by timmackey** [aljazsim/vs-code-typescript-class-organizer#4]
public @HostListener('window:resize', ['$event'])
    onResize(event?) {

...is invalid.  causes errors:
[ts] Duplicate identifier 'public'.
...and...
[tslint] Declaration of instance field not allowed after declaration of instance method. Instead, this should come at the beginning of the class/interface. (member-ordering)"

Suggestion:  test the organizer agains TSLint 1.0.39 or greater.  TSLint has 8.9M downloads.
I really like this organizer and hope you continue to improve the product.

**Comment by aljazsim** [comment]
Fixed issue with decorators, try it out in version 1.0.9.
