### ISSUE TITLE
Also reorganizes the ngoninit in angular applications

### ISSUE THREAD

**Issue by IceCrew-Source** [aljazsim/vs-code-typescript-class-organizer#44]
Hi!

I love this extension but there is one thing that totally frustrates me: 
when the extension organize the file, it change also the place of the functions ngOnInit and ngOnDestroy of my angular app.
Would there be a way not to change the order of these functions in relation to the others? With the memberOrder for example?

Thank you in advance!

**Comment by aljazsim** [comment]
Done, please see README to see how to use the placeAbove and placeBelow settings!
