### ISSUE TITLE
Adding Config to Remove Regions, etc

### ISSUE THREAD

**Issue by mike2071** [aljazsim/vs-code-typescript-class-organizer#50]
I have had this setup before to not add public and hide regions, etc, I cannot seem to get it right, can you give me a clear example of how to structure the json please?

**Comment by aljazsim** [comment]
Hi Mike. I'm not sure I understand your questions. You'd like to know how to configure settings in VS code?

![image](https://github.com/aljazsim/vs-code-typescript-class-organizer/assets/36719693/99eb3a8f-72e7-4891-a060-1a2e4afd6d60)
