### ISSUE TITLE
Accesssors are broken when reorganizing

### ISSUE THREAD

**Issue by Jamesernator** [aljazsim/vs-code-typescript-class-organizer#52]
Using an [accessor](https://devblogs.microsoft.com/typescript/announcing-typescript-4-9/#auto-accessors-in-classes) such as:

```ts
class Example {
    accessor name = "value";
}
```

when run through the class organizer it incorrectly generates the following:

```ts
export default class Example {
    accessor
    name = "value";
}
```

which gets interpreted as (due to ASI) as:

```ts
export default class Example {
    accessor;
    name = "value";
}
```

**Comment by aljazsim** [comment]
Done. Give it a try in version 1.0.27!
