### ISSUE TITLE
Feature request: Organize modules

### ISSUE THREAD

**Issue by NatoBoram** [aljazsim/vs-code-typescript-class-organizer#53]
It's common to write modules instead of classes nowadays as you probably don't need to use classes in most cases.

Random example:

https://github.com/jdalrymple/gitbeaker/blob/ee1436e9634381d03a2c3ad9ca03de3901e65231/packages/rest/src/Requester.ts#L1-L135

In this file, there's some exported functions, some unexported functions, an exported constant... Basically, the same things you'd find in a class, except maybe a constructor.

While it would be possible to wrap the entire thing with `class X {}`, replace `export function` with `public` then `function` with `private`, sort it, then remove the class and change back the accessors, it would be much simpler if this extension could do it.

**Comment by aljazsim** [comment]
Hi Nato. I was actually about to implement sorting of members outside of classes as well, the problem was that functions in such files could depend on other functions in the same file and ordering would brake the code as a function could be referencing a different function that has not yet been defined.

**Comment by NatoBoram** [comment]
I wasn't able to reproduce the problem.

**index_test.ts**
```ts
function dependOnMeBefore() {
	console.log("before")
}

export function exportedFunction() {
	dependOnMeBefore()
	dependOnMeAfter()
}

function dependOnMeAfter() {
	console.log("after")
}
```

**index.ts**
```ts
import { exportedFunction } from "./index_test"

exportedFunction()
```

**output**
```ts
❯ bun src/index.ts
[0.03ms] ".env.local", ".env"
before
after
```
```ts
❯ tsx ./src/index.ts
before
after
```
```ts
❯ tsc && node ./dist/index.js
before
after
```

**Comment by aljazsim** [comment]
I'll have a look

**Comment by aljazsim** [comment]
Done. You can try it out in version 1.0.27!

**Comment by NatoBoram** [comment]
Thanks. This is brilliant!
