### ISSUE TITLE
Sorting should respect custom regions

### ISSUE THREAD

**Issue by VictorOdukoya** [aljazsim/vs-code-typescript-class-organizer#59]
I noticed that you can make tsco create regions for different member types. Which is great, but it would be nice, if the extension would have the capability to also respect custom regions. Somtimes I want to group specific types of methods inside of a region and have them show up on top of all the other class methods. Is that possible? For example, in angular I wrap my hooks inside of a region and I want them to always be on top of my other methods. I don't believe that that is currently working, is it?

`
  /* #region hooks */
 ngOnDestroy() {
    this.subscriptions.forEach((sub) => sub.unsubscribe());
  }

  ngOnInit() {
    this.initializeEmptyForm();
    this.initLoadingSubscription();
...
  }
/* #endregion */

//all other methods here....
`

**Comment by aljazsim** [comment]
Hi Victor. This is by design. Whenever organizing a file, it removes all regions and regenerates them accordingly. If it allowed for custom regions, the whole ordering system would fall apart as the extensions is not looking for regions when organizing, but for members.
