### ISSUE TITLE
BUG: Decorator handling is broken

### ISSUE THREAD

**Issue by rhnatiuk** [aljazsim/vs-code-typescript-class-organizer#65]
If you run on a class that has a field with the same name as the string used in its decorator, e.g.,

```TypeScript
class X {
   @ViewChild("canvas") canvas: xxx;
}
```

the result will be

```TypeScript
class X {
   @ViewChild("public canvas") canvas: xxx;
}
```

instead of the expected

```TypeScript
class X {
   @ViewChild("canvas") public canvas: xxx;
}
```

This is quite a significant problem, as it breaks the code.

**Comment by aljazsim** [comment]
Hi Roman. 

Thank you for reporting the issue. Please give it another try in version 1.0.29 and let me know if this has been resolved.

**Comment by rhnatiuk** [comment]
Hi! Yes, now it seems to work well! Thank you!
