### ISSUE TITLE
cluster property decorators together

### ISSUE THREAD

**Issue by timmackey** [aljazsim/vs-code-typescript-class-organizer#7]
Instead of producing this:

    ComponentClassName = 'TtmDatagridComponent';
    currentYear: number;
    dialogHeader: string;
    displayExportDialog: boolean;
    errorMessage: string;
    @Input() frameInfo: FrameInfo;
    @Output() modalSave: EventEmitter<any> = new EventEmitter<any>();
    ngClass_body = 'ngClass_body';
    progressbarIsVisible = false;
    progressbarLabel = 'Creating Test \'Midterm\'';
    progressbarPercent = 63;
    showemptymessage = true;
    source: any = null;
    subscription: any = null;
    @ViewChild('tableData') tableData: Table;
    @ViewChild(TtmDialogConfirmComponent) ttmDialogConfirmComponent: TtmDialogConfirmComponent;
    @ViewChild(TtmDialogErrorComponent) ttmDialogErrorComponent: TtmDialogErrorComponent;
    @ViewChild(TtmDialogImportComponent) ttmDialogImportComponent: TtmDialogImportComponent;

Produce this:

    @Input() frameInfo: FrameInfo;
    @Output() modalSave: EventEmitter<any> = new EventEmitter<any>();
    @ViewChild('tableData') tableData: Table;
    @ViewChild(TtmDialogConfirmComponent) ttmDialogConfirmComponent: TtmDialogConfirmComponent;
    @ViewChild(TtmDialogErrorComponent) ttmDialogErrorComponent: TtmDialogErrorComponent;
    @ViewChild(TtmDialogImportComponent) ttmDialogImportComponent: TtmDialogImportComponent;

    ComponentClassName = 'TtmDatagridComponent';
    currentYear: number;
    dialogHeader: string;
    displayExportDialog: boolean;
    errorMessage: string;
    ngClass_body = 'ngClass_body';
    progressbarIsVisible = false;
    progressbarLabel = 'Creating Test \'Midterm\'';
    progressbarPercent = 63;
    showemptymessage = true;
    source: any = null;
    subscription: any = null;

Note the extra line between decorators and the remainder property list.

**Comment by aljazsim** [comment]
So if I understand correctly, you want the option of having properties with decorators in a separate group?

**Comment by aljazsim** [comment]
Would this make sense in a non Angular environment? After all decorators are members metadata, and members are ordered alphabetically regardless. How would this work with members with multiple decorators?

**Comment by timmackey** [comment]
I don't know enough about non Angular environments to comment.  Having the option to group decorated symbols together would be desirable for Angular environments.  Order by decorator symbol ASCII code value.  (i.e. '@' before 'A'.   Also, consider an option to order by case-sensitivity.  (i.e. 'C' before 'a') Thanks.

**Comment by aljazsim** [comment]
Try it out in version 1.0.10. The new setting is groupPropertiesWithDecorators.

**Comment by timmackey** [comment]
A vast improvement.   THANK YOU!

Would still prefer to see decorated symbols at the top of the list.  This is the result I get:

    private sourceHeader: string;
    private targetHeader: string;

    @ViewChild(TtmDialogErrorComponent) public ttmDialogErrorComponent: TtmDialogErrorComponent;
    ComponentClassName = 'TtmPicklistComponent';
    public any;
    public source: any[];
    public target: any[];

**Comment by aljazsim** [comment]
The config groupPropertiesWithDecorators is set to false by default. I'm guessing that is probably the reason.

**Comment by aljazsim** [comment]
If I understand correctly you'd just like a new line in between?

**Comment by aljazsim** [comment]
And a custom ordering configuration?

**Comment by timmackey** [comment]
I would prefer symbols grouped in this order:
1. Decorated symbols
2. public
3. private
 (public before private, same as functions/methods order - just like the sample supplied)

**Comment by aljazsim** [comment]
I've added a new line between the nodes with decorators and the nodes without. They however have to remain in the same region, since they are all properties (in your example). Example:

    // #region Properties (5)

    @decorator1()
    public property1;
    @decorator2()
    public property2;
    @decorator3()
    public property3;

    public property4;
    public property5;

    // #endregion Properties (5)

I do not make explicit regions for public properties, public static properties, public readonly properties, etc., since that would produce in my opinion too many regions. But I do still group them together by access modifiers, static / instance, write mode and so on. That is why properties with decorators stay within that "group", but are now moved to the top respective group and separated by a new line.

**Comment by timmackey** [comment]
The setting "Group Properties With Decorators"
[  ] When true properties with decorators will come first.
------
Properties with decorators are grouped together within a region, however, those properties don't come first.  The grouping order is private, decorators, public.
If the grouping order were actually decorators, and then public or private that would make more sense.
Thanks for giving this your attention.
