### ISSUE TITLE
@NgModule is defined before @Component

### ISSUE THREAD

**Issue by timmackey** [aljazsim/vs-code-typescript-class-organizer#8]
@NgModule must be defined AFTER @Component to avoid undefined symbols.
Example:

@Component({
    selector: 'ttm-pickList',
    templateUrl: 'picklist.html',
    styleUrls: ['picklist.css',
    ],
})
export class TtmPickList implements AfterViewChecked, AfterContentInit, OnInit {
 ...
}

@NgModule({
    imports: [
        CommonModule,
        ButtonModule,
        SharedModule,
        NgToggleModule,
    ],
    exports: [
        TtmPickList,
        SharedModule
    ],
    declarations: [
        TtmPickList
    ]
})
export class PickListModule { }

When @NgModule (and exported symbols) are defined in @Component and the order is as currently implemented, then symbol 'TtmPickList' is undefined.  The user must manually relocate the @NgModule class/code  after @Component.

**Comment by aljazsim** [comment]
The issue here is that I am performing syntactic analysis of the code and not a semantic one. If you want your component to be referenced correctly I'd suggest to either move it to a new file or set the decorator to @Component instead of @component (that way C would come before N).
