### ISSUE TITLE
Cannot organize a file a second time

### ISSUE THREAD

**Issue by timmackey** [aljazsim/vs-code-typescript-class-organizer#9]
Cannot 're-organize' a file.  Duplicate #region and #endregion tags are created when an organized file is organized.

**Comment by aljazsim** [comment]
Please test the bug fix in version 1.0.11. I've also added a new line between groups of elements with decorators and the groups without. And grouping by decorators now applies to all node types, not just properties.

**Comment by timmackey** [comment]
No more duplicate #regions.  Thank you.
Please see my reply to other issue.
